### ISSUE TITLE
Use vector icon

### ISSUE THREAD

**Issue by arai-a** [mrgiggles/histoire#14]
separated from https://github.com/mrgiggles/histoire/pull/13

if we want to use unit like `em` for icon, the icon needs to be vector image (either SVG image or icon font).
for accessibility, SVG image with `alt` attribute might be better than icon font,
unless we can use ligature magic or something

**Comment by arai-a** [comment]
or perhaps we can just use U+270F ✏ (haven't yet checked how it's shown on other environments)

**Comment by arai-a** [comment]
> or perhaps we can just use U+270F ✏ (haven't yet checked how it's shown on other environments)

this doesn't look nice on my debian desktop (just like the image on https://www.charbase.com/270f-unicode-pencil )

**Comment by bnjbvr** [comment]
Maybe we could use [Fort Awesome](https://fortawesome.com/)?

**Comment by bnjbvr** [comment]
Or Font Awesome which is free: https://fontawesome.com/icons?d=gallery&q=pencil

**Comment by arai-a** [comment]
Thanks!
Looks like there's guide for accessibility too.
https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility

I'll try
