### ISSUE TITLE
Allow to display updates by periods

### ISSUE THREAD

**Issue by bnjbvr** [mrgiggles/histoire#22]
Currently, we only display updates from the previous month. It'd be nice to be able to select a time range to choose which period to look at.

The simplest way to implement this would be to use a select tag with predefined ranges. The hardest way would be a two-handles slider which allow to select a precise range; or something like http://airbnb.io/react-dates/.

**Comment by arai-a** [comment]
We already have `start` and `end` query parameters (in seconds) that can specify the range.
It just needs UI.
